version: 2 # use CircleCI 2.0
jobs: # a collection of steps
    build: # runs not using Workflows must have a `build` job as entry point
        docker: # run the steps with Docker
            - image: circleci/node:4.8.2 # ...with this image as the primary container; this is where all `steps` will run
        steps: # a collection of executable commands
            - checkout # special step to check out source code to working directory
            - run:
                  name: npm-i
                  command: npm install
            - run: # run tests
                  name: test
                  command: npm test
    deploy:
        docker:
            - image: buildpack-deps:trusty
        steps:
            - checkout
            - run:
                  name: Deploy Master to Heroku
                  command: |
                      git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only: master
